### ISSUE TITLE
무작위 이벤트 응모 방지를 위해 구글 Recaptcha 리켑차 추가 부탁드립니다.

### ISSUE THREAD

**Issue by MinGWon** [horyu1234/HusuabieEventLotteryApply#4]
무작위 이벤트 응모 방지를 위해 구글 Recaptcha 리켑차 추가 부탁드립니다.

**Comment by horyu1234** [comment]
이벤트 응모 사이트에 관심을 가져주셔서 감사드립니다.

캡챠 인증 기능은 구독자분들이 응모하시면서 생길 수 있는 불편한 점들로 인하여,
예전에 허수아비님과 상의 하에 추가하지 않기로 결정된 기능이였습니다.

생성해주신 이슈에 대하여 허수아비님과 다시 한번 의논하여, 현재 Google Invisible Recaptcha 를 적용하는 것으로 결정되었습니다.

이슈는 캡챠가 추가되면 닫도록 하겠습니다.

**Comment by dalbodeule** [comment]
@horyu1234 결국엔 캡챠를 다는걸로 일단락됬군요
