### ISSUE TITLE
요즈음 자바프로그래밍을 전문적으로 배우고 있는 사람입니다. 질문 한가지만 하려고 해서 남깁니다.

### ISSUE THREAD

**Issue by KimTaeMin96** [horyu1234/HusuabieEventLotteryApply#5]
이 프로젝트 개발하실때 개발환경이 어떻게 하셨는지 궁금하고 이프로젝트에 대한 분석은 추후 배우게될 스프링프레임워크가 있어 한번 공부해보려는데 윈도우 7에선 datasource에 url쪽에서 오류가나 진행이 않되는거보아 윈도우에선 빌드가 않되나 싶습니다.

개발자분은 이프로젝트를 진행함으로서 개발환경을 어떻게 하셨는지 궁금합니다

**Comment by horyu1234** [comment]
Database: MariaDB
Java version: 1.8
IDE: Intellij Ultimate Edition
OS: Windows 10 Pro

개발 환경은 이렇습니다.

datasource 관련 오류는 application.yml 파일에서 데이터베이스 부분 설정을 본인 데이터베이스에 맞도록 설정해주셔야 합니다.

**Comment by KimTaeMin96** [comment]
이해는 했으나 IDE툴이 유로라고 하는거 같은데...

**Comment by horyu1234** [comment]
@ktm0609 IDE 는 본인이 사용하시기 편리하신 것으로 진행하시면 됩니다.

**Comment by KimTaeMin96** [comment]
IDE툴은 Spring Tool Suite로 사용해도 무방한가요?

**Comment by horyu1234** [comment]
@ktm0609 해당 툴은 사용해본 적이 없어, 답변이 힘듭니다.

**Comment by KimTaeMin96** [comment]
지금까지 테스트 하고는 있습니다만 관리자 페이지 아이디 암호 설정을 어떻게 진행하니요?

**Comment by horyu1234** [comment]
@ktm0609 현재는 별도로 회원가입 페이지가 존재하지 않습니다.

관리자 계정을 추가하시기 위해서는 프로젝트에 임의로 테스트 클래스를 생성하신 후

`System.out.println(BCrypt.hashpw("아이디/비밀번호", BCrypt.gensalt(15)));`

위의 소스를 실행하여 나온 해쉬값을 account 테이블에 직접 넣어주셔야 합니다.

**Comment by KimTaeMin96** [comment]
EVENT_START_TIME, EVENT_END_TIME의 DB에 무슨값이 들어가야하나요?
값을몰라 해메고 있습니다.(값을 보여주셨으면...)

**Comment by horyu1234** [comment]
@ktm0609 
```
INSERT INTO `EVENT` (`EVENT_ID`, `EVENT_TITLE`, `EVENT_DETAIL`, `EVENT_STATUS`, `EVENT_START_TIME`, `EVENT_END_TIME`) VALUES
	(1, '테스트 이벤트', '세부 일정을 입력해주세요.', 'OPEN', '2018-06-30 22:00:00', '2018-08-30 22:00:00');
```

쿼리를 실행하셔서 초기 1회의 이벤트만 추가해두시면, 이후 부터는 이벤트 설정 메뉴에서 버튼 클릭 한번 만으로 다음 이벤트로 넘어갈 수 있습니다.

**Comment by KimTaeMin96** [comment]
java.time.format.DateTimeParseException: Text '2018-06-30 22:00:00' could not be parsed at index 19
localhost:443/admin/eventSetting/ 에접속시 오류가 뜹니다

**Comment by horyu1234** [comment]
@ktm0609 
CREATE TABLE 쿼리에서 업데이트 되지 않은 사항이 있었네요. 이 부분은 별도의 커밋으로 수정하도록 하겠습니다.

`EVENT_START_TIME` 와 `EVENT_END_TIME` 의 컬럼 타입을 DATETIME 으로 설정하시면 됩니다.

**Comment by KimTaeMin96** [comment]
이정도로하면 다른분들 테스트 하실때 오류 사항없이 될거 같아 이메세지를 기해 이슈를 Close하겠습니다.
