### ISSUE TITLE
7/7일 문의 드렸던 사람입니다.

### ISSUE THREAD

**Issue by jinshoogun** [horyu1234/HusuabieEventLotteryApply#6]
안녕하세요. 
유튜브채널에다가 메신저를 넣었는데 잘 안 읽으신거 같아서 여기다가 올립니다.

다름 아니라 개인적으로 NAS 구입하려고 생각하고 있습니다.
용도는 Mysql / WAS / FTP 일단 요정도로 구성을 하려고 합니다.

그래서 어느정도 검색해서 정보를 얻고 있었는데요. 마침 환경이 비슷할 것 같아서 개인적으로 문의를 드립니다. 유튜브에 메시지 보냈으니 여기 대신 그 주소로 답변드려도 괜찮습니다.

해당 PC 스펙을 간략히 알고 싶습니다. 간략히 어떻게 견적을 냈는지 요정도?입니다. 혹시 지금 사용하시는 용도가 주로 어떤 위주인지도 알고 싶습니다.

늦은시간에 급히 보내서 죄송합니다.

**Comment by FauxSeal210** [comment]
@jinshoogun ㄹㄹ

**Comment by horyu1234** [comment]
@jinshoogun 여러 분들이 문의하신 것들을 계속 기억하기는 힘듭니다.

어떤 것을 문의하셨는지 말씀 부탁드립니다.

**Comment by jinshoogun** [comment]
죄송합니다 작성도중 실수로 엔터를 눌러서요. ^^;
jinshoogun@gmail.com 답변 주시면 됩니다

**Comment by horyu1234** [comment]
메일로 답변 드렸습니다.

이와 관련하여 추가 질문이 있으시다면 메일로 부탁드립니다.
